from __future__ import annotations

from app.agents.base import AgentContext, BaseAgent
from app.models.schemas import Finding


class ReportWriterAgent(BaseAgent):
    name = "report"
    description = "Adds reporting metadata and next-step guidance."

    def run(self, context: AgentContext) -> list[Finding]:
        engagement = context.get("engagement", {})
        return [
            Finding(
                title="Engagement report package ready",
                severity="info",
                category="reporting",
                description=f"The local report set for '{engagement.get('name', 'engagement')}' can be exported as Markdown, HTML, PDF, JSON, CSV, executive summary, Jira text, or GitHub issue text.",
                evidence=["No SARIF export is generated by design."],
                remediation="Share technical reports with engineering owners and executive summaries with leadership stakeholders.",
                confidence="high",
            )
        ]
